### ISSUE TITLE
[BUG] Not working with ProtocolLib

### ISSUE THREAD

**Issue by stijnb1234** [magmafoundation/Magma#112]
**Describe the bug**
I give an error spam when using ProtocolLib.

```
> [15:27:27 WARN]: [ProtocolLib] Encountered a LinkageError. Make sure you're not using this jar for multiple server instances!
> [15:27:27 WARN]: [ProtocolLib] If you're getting this error for other reasons, please report it!
> [15:27:27 WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.events.PacketContainer
> [15:27:27 WARN]: at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:297)
> [15:27:27 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378)
> [15:27:27 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64)
> [15:27:27 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343)
> [15:27:27 WARN]: at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313)
> [15:27:27 WARN]: at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
> [15:27:27 WARN]: at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
> [15:27:27 WARN]: at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:247)
> [15:27:27 WARN]: at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:179)
> [15:27:27 WARN]: at net.minecraft.network.NetworkManager.func_150732_b(NetworkManager.java:247)
> [15:27:27 WARN]: at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java:179)
> [15:27:27 WARN]: at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:1347)
> [15:27:27 WARN]: at net.minecraft.entity.EntityTrackerEntry.func_151259_a(EntityTrackerEntry.java:392)
> [15:27:27 WARN]: at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:296)
> [15:27:27 WARN]: at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:296)
> [15:27:27 WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:988)
> [15:27:27 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
> [15:27:27 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851)
> [15:27:27 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:723)
> [15:27:27 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. Install ProtocolLib
2. Install a plugin that uses it
3. See error

**Expected behavior**
No error, and it should just work.

**Info (please complete the following information):**
- Mod Name: -
 - Mod Version: - 
 - Magma Version: Magma Dev master-0e43213
 - OS: Linux (Ubuntu)

**Comment by stijnb1234** [comment]
I also get this error:
```
> [15:44:02 WARN]: java.lang.NoSuchMethodException: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(net.minecraft.network.Packet)
> [15:44:02 WARN]: at java.lang.Class.getDeclaredMethod(Class.java:2130)
> [15:44:02 WARN]: at org.magmafoundation.magma.remapper.proxy.ProxyClass.getDeclaredMethod(ProxyClass.java:30)
> [15:44:02 WARN]: at me.wouter.minetopia.utils.reflect.wkMvHiTHLyqFIhJ.I(mc:117)
> [15:44:02 WARN]: at me.wouter.minetopia.utils.reflect.wkMvHiTHLyqFIhJ.wkMvHiTHLyqFIhJ(mc:143)
> [15:44:02 WARN]: at me.wouter.minetopia.utils.plugin.httHooAopOc0CwK$e.run(li:401)
> [15:44:02 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78)
> [15:44:02 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
> [15:44:02 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [15:44:02 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [15:44:02 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [15:44:02 WARN]: at java.lang.Thread.run(Thread.java:748)
> [15:44:02 WARN]: java.lang.NoSuchMethodException: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_147359_a(net.minecraft.network.Packet)
> [15:44:02 WARN]: at java.lang.Class.getDeclaredMethod(Class.java:2130)
> [15:44:02 WARN]: at org.magmafoundation.magma.remapper.proxy.ProxyClass.getDeclaredMethod(ProxyClass.java:30)
> [15:44:02 WARN]: at me.wouter.minetopia.utils.reflect.wkMvHiTHLyqFIhJ.I(mc:117)
> [15:44:02 WARN]: at me.wouter.minetopia.utils.reflect.wkMvHiTHLyqFIhJ.wkMvHiTHLyqFIhJ(mc:143)
> [15:44:02 WARN]: at me.wouter.minetopia.utils.plugin.httHooAopOc0CwK$e.run(li:401)
> [15:44:02 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78)
> [15:44:02 WARN]: at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
> [15:44:02 WARN]: at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [15:44:02 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [15:44:02 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [15:44:02 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by SauROnmiKE** [comment]
I am also having the console spammed with the same error.

**Comment by red0fireus** [comment]
I submitted an Issue/Bug with ProtocolLib:
I'm getting similar issues.

https://github.com/dmulloy2/ProtocolLib/issues/825

**Comment by red0fireus** [comment]
This issue has been fixed!
Use the latest dev build
