### ISSUE TITLE
server starting error

### ISSUE THREAD

**Issue by maplol** [magmafoundation/Magma#123]
[19:49:14 ERROR]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@2532f74b:
 java.lang.NoClassDefFoundError: org/lwjgl/opengl/GL11
        at com.mic.testmod.blocks.machine.watersource.BlockWaterSource.<init>(BlockWaterSource.java:40) ~[BlockWaterSource.class:?]
        at com.mic.testmod.init.ModBlocks.<clinit>(ModBlocks.java:52) ~[ModBlocks.class:?]
        at com.mic.testmod.util.handlers.RegistryHandler.onBlockRegister(RegistryHandler.java:35) ~[RegistryHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_RegistryHandler_onBlockRegister_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:5fab8b3]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:146) ~[EventBus$1.class:5fab8b3]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:5fab8b3]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:851) [GameData.class:5fab8b3]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:601) [Loader.class:5fab8b3]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:103) [FMLServerHandler.class:5fab8b3]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335) [FMLCommonHandler.class:5fab8b3]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:169) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: org.lwjgl.opengl.GL11
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_251]
        ... 14 more
[19:49:14 ERROR]: Index: 19 Listeners:
[19:49:14 ERROR]: 0: NORMAL
[19:49:14 ERROR]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@155bf2b9
[19:49:14 ERROR]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@77d77e1a
[19:49:14 ERROR]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@456d5704
[19:49:14 ERROR]: 4: net.minecraftforge.fml.common.eventhandler.EventBus$1@54668bfd
[19:49:14 ERROR]: 5: net.minecraftforge.fml.common.eventhandler.EventBus$1@1ee265f2
[19:49:14 ERROR]: 6: net.minecraftforge.fml.common.eventhandler.EventBus$1@5209ff9a
[19:49:14 ERROR]: 7: net.minecraftforge.fml.common.eventhandler.EventBus$1@7df357a8
[19:49:14 ERROR]: 8: net.minecraftforge.fml.common.eventhandler.EventBus$1@1d2a0288
[19:49:14 ERROR]: 9: net.minecraftforge.fml.common.eventhandler.EventBus$1@106a292a
[19:49:14 ERROR]: 10: net.minecraftforge.fml.common.eventhandler.EventBus$1@d82f192
[19:49:14 ERROR]: 11: net.minecraftforge.fml.common.eventhandler.EventBus$1@6a2ba99d
[19:49:14 ERROR]: 12: net.minecraftforge.fml.common.eventhandler.EventBus$1@27d8c812
[19:49:14 ERROR]: 13: net.minecraftforge.fml.common.eventhandler.EventBus$1@66ba96ba
[19:49:14 ERROR]: 14: net.minecraftforge.fml.common.eventhandler.EventBus$1@7caef59e
[19:49:14 ERROR]: 15: net.minecraftforge.fml.common.eventhandler.EventBus$1@4b7edcd7
[19:49:14 ERROR]: 16: net.minecraftforge.fml.common.eventhandler.EventBus$1@2a0705f2
[19:49:14 ERROR]: 17: net.minecraftforge.fml.common.eventhandler.EventBus$1@18ba494e

**Comment by maplol** [comment]
mods list: https://ibb.co/r3cTZwr

**Comment by Hexeption** [comment]
This is a issue with the mod not magma
