### ISSUE TITLE
[Issue] Undescriptive error on startup: InvalidPluginException

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [magmafoundation/Magma#130]
**Background**
I'm a Spigot plugin developer and a user contacted me with an error (see screenshot in the screenshots section below). After testing, I verified the plugin to be working correctly with Magma and the issue was caused by the admin himself. 

**Describe the issue**
When a plugin is dropped in both the plugins and mods folder, an undescriptive error is thrown in the console and the plugin does not get enabled. I had no idea what caused this issue as the plugin version he was using was compatible with Bukkit 1.12. It took me some time to track it down. The error does not seem to be thrown when the plugin is only in the mods folder. 

**To Reproduce**
1. Download a Spigot (possibly any) plugin. In this case, [BetterSleeping](https://www.spigotmc.org/resources/bettersleeping-1-12-1-15.60837/)
2. Drop the plugin in the plugins folder
3. Drop the plugin in the mods folder
4. Start the server

**Expected behavior**
I'm not sure to what extent this is possible but showing a more descriptive error in this case would be handy for plugin devs. Albeit quite rare, misconfiguration happens every now and then. The current error made me believe that there was something wrong with the plugin itself. If possible, it would be nice if the plugin could be enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/37397560/82664914-0470fc00-9c33-11ea-99f9-e0311a613fbf.png)

**Info (please complete the following information):**
-  ~~Mod Name~~: Not applicable
 - ~~Mod Version~~: Not applicable
 - Magma Version: latest build of 1.12
 - OS: Windows

**Additional context**
The same error again, in text form.
```
[13:59:02 ERROR]: Could not load 'plugins\BetterSleeping-2.6.2.jar' in folder 'plugins'
 org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[JavaPluginLoader.class:aed4e40]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:aed4e40]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:250) [SimplePluginManager.class:aed4e40]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:322) [CraftServer.class:aed4e40]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:414) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalStateException: JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:42) ~[JavaPlugin.class:aed4e40]
        at be.dezijwegel.BetterSleeping.<init>(BetterSleeping.java:31) ~[BetterSleeping.class:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:84) ~[PluginClassLoader.class:aed4e40]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:123) ~[JavaPluginLoader.class:aed4e40]
        ... 7 more
```

**Comment by kwright02** [comment]
Fix: Plugins go in the plugins folder, not the mods folder
