### ISSUE TITLE
[BUG + ERROR] Aroma portal

### ISSUE THREAD

**Issue by Neewen** [magmafoundation/Magma#138]
**Describe the bug**

When we use the aroma portal in overworld to go to the aroma dimension, there is an error and no portal once teleport and sometimes we get kicked for "Internal Server Error".

**To Reproduce**

Record: https://youtu.be/0NP7dNQJ5iI

The error:

> [16:12:09 FATAL]: Error executing task
>  java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Colliding entity with block
>         at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
>         at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:925) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:734) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
> Caused by: net.minecraft.util.ReportedException: Colliding entity with block
>         at net.minecraft.entity.Entity.func_70091_d(Entity.java:700) ~[vg.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:767) ~[pa.class:?]
>         at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) ~[lk.class:?]
>         at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(CPacketPlayer.java:76) ~[lk$a.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
>         at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
>         ... 5 more
> Caused by: java.lang.NullPointerException
>         at aroma1997.world.dimension.TeleporterMining.func_85188_a(TeleporterMining.java:278) ~[TeleporterMining.class:?]
>         at aroma1997.world.dimension.TeleporterMining.func_180266_a(TeleporterMining.java:42) ~[TeleporterMining.class:?]
>         at net.minecraft.world.Teleporter.placeEntity(Teleporter.java:521) ~[anc.class:?]
>         at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:912) ~[oq.class:?]
>         at aroma1997.core.misc.TeleporterNormal.teleportToDimension(TeleporterNormal.java:82) ~[TeleporterNormal.class:?]
>         at aroma1997.core.misc.TeleporterNormal.teleportToDimension(TeleporterNormal.java:74) ~[TeleporterNormal.class:?]
>         at aroma1997.world.item.BlockMiningPortal.func_180634_a(BlockMiningPortal.java:83) ~[BlockMiningPortal.class:?]
>         at net.minecraft.entity.Entity.func_145775_I(Entity.java:1197) ~[vg.class:?]
>         at net.minecraft.entity.Entity.func_70091_d(Entity.java:694) ~[vg.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:767) ~[pa.class:?]
>         at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) ~[lk.class:?]
>         at net.minecraft.network.play.client.CPacketPlayer$Position.func_148833_a(CPacketPlayer.java:76) ~[lk$a.class:?]
>         at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
>         at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
>         at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
>         ... 5 more

**Expected behavior**
The expected behaviour is to NOT have this message and the portal should generate inside the aroma dimension, instead it doesn't generate.

**Info (please complete the following information):**
- Mod Name and version:
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b89
Aroma1997Core-1.12.2-2.0.0.2
 - Magma Version: 
Magma version 3d116a0 (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge Version 14.23.5.2854)
 - OS:
Windows 10 (But on a Linux server it's the same)

**Additional context**

try without magma:

Record: https://youtu.be/_64Ovoh5UII

**Comment by kwright02** [comment]
It seems that it's having some Null Exception when trying to place the portal or something around that. I'll investigate and get back to you on this.

**Comment by zanda8893** [comment]
Hi, I'm getting this error as well on that latest version of magma.
`[15:49:46] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
 java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Colliding entity with block
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: net.minecraft.util.ReportedException: Colliding entity with block
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:700) ~[vg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:769) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) ~[lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(CPacketPlayer.java:110) ~[lk$b.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.NullPointerException
        at aroma1997.world.dimension.TeleporterMining.func_85188_a(TeleporterMining.java:278) ~[TeleporterMining.class:?]
        at aroma1997.world.dimension.TeleporterMining.func_180266_a(TeleporterMining.java:42) ~[TeleporterMining.class:?]
        at net.minecraft.world.Teleporter.placeEntity(Teleporter.java:784) ~[anc.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:910) ~[oq.class:?]
        at aroma1997.core.misc.TeleporterNormal.teleportToDimension(TeleporterNormal.java:82) ~[TeleporterNormal.class:?]
        at aroma1997.core.misc.TeleporterNormal.teleportToDimension(TeleporterNormal.java:74) ~[TeleporterNormal.class:?]
        at aroma1997.world.item.BlockMiningPortal.func_180634_a(BlockMiningPortal.java:83) ~[BlockMiningPortal.class:?]
        at net.minecraft.entity.Entity.func_145775_I(Entity.java:1201) ~[vg.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:694) ~[vg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:769) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(CPacketPlayer.java:33) ~[lk.class:?]
        at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(CPacketPlayer.java:110) ~[lk$b.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more`
