### ISSUE TITLE
[Issue] SkyFactory 4 drop player after join server

### ISSUE THREAD

**Issue by kretowicz14** [magmafoundation/Magma#146]
**Describe the issue**
When join on server, i get disconecting and have error
```
java.lang.NullPointerException: null
	at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:574) ~[pl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1308) ~[pa.class:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:471) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:231) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1011) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:734) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**To Reproduce**
1. move all files magma server files, to unpacked SkyFactory server 4 
2. Start with command "java -Xms4192M -Xmx7288M -jar Magma-aed4e40-server.jar nogui"
3. Join to server with new created world
4. Get error in log file

**Info (please complete the following information):**
- SkyFactory_4_Server_4.1.0
- Windows / ubuntu 18.10:

[latest.log] (https://mclo.gs/gK9swU9)

**Comment by kretowicz14** [comment]
Can't paste full last log via mclo.gs, so i upload: https://drive.google.com/file/d/1RVdf17Qvt4rbqYysmF5xMM9S-gINDiCE/view?usp=sharing

**Comment by Hexeption** [comment]
This is an issue with fast workbench to fix use the config on the discord

**Comment by kretowicz14** [comment]
Thank you, i will check solution.
