### ISSUE TITLE
[BUG] [PLUGIN] Ultimate Kits 

### ISSUE THREAD

**Issue by Hexeption** [magmafoundation/Magma#159]
**Describe the bug**
Error when trying to use ultimate kits plugin, seems to have issues with InventoryClickEvent

**Additional context**
```java
[14:11:41] [Server thread/ERROR] [Minecraft]: Could not pass event InventoryClickEvent to UltimateKits v2.5.1
org.bukkit.event.EventException: null
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:39) ~[MethodHandleEventExecutor.class:d8c5244]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:d8c5244]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:d8c5244]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2155) [pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:902) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:839) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:711) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayerMP.nextContainerCounter()I
        at com.songoda.ultimatekits.core.nms.v1_12_R1.AnvilView.open(AnvilView.java:170) ~[?:?]
        at com.songoda.ultimatekits.core.gui.AnvilGui.open(AnvilGui.java:49) ~[?:?]
        at com.songoda.ultimatekits.core.gui.GuiManager.showGUI(GuiManager.java:95) ~[?:?]
        at com.songoda.ultimatekits.gui.KitGuiOptionsGui.lambda$paint$3(KitGuiOptionsGui.java:76) ~[?:?]
        at com.songoda.ultimatekits.core.gui.Gui.onClick(Gui.java:809) ~[?:?]
        at com.songoda.ultimatekits.core.gui.GuiManager$GuiListener.onClickGUI(GuiManager.java:221) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:d8c5244]
        ... 14 more
```

**Comment by kwright02** [comment]
@Hexeption how is this issue magma related?

**Comment by kwright02** [comment]
Fixed in future release
