### ISSUE TITLE
[BUG] dtlTraders Plugin Error

### ISSUE THREAD

**Issue by link1107** [magmafoundation/Magma#161]
I get this error when i use _/dtl edit_ command and then press button "Create new shop" (dtlTraders plugin, version 6.0.7):

[https://sun6-16.userapi.com/8srWScQvN05wyok9ppz2yN5ngqehOVJIBmIuXg/BIeARqKcrHs.jpg](url)

[20:04:59 ERROR]: Could not pass event InventoryClickEvent to dtlTraders v6.0.7
java.lang.NoSuchMethodError: net.minecraft.entity.player.EntityPlayerMP.nextContainerCounter()I
at net.wesjd.anvilgui.version.Wrapper1_12_R1.getNextContainerId(Wrapper1_12_R1.java:21) ~[?:?]
at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:163) ~[?:?]
at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:146) ~[?:?]
at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[?:?]
at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:380) ~[?:?]
at com.degitise.minevid.dtlTraders.guis.guiservices.ShopEditService$1.onClick(ShopEditService.java:415) ~[?:?]
at com.degitise.minevid.dtlTraders.customInventory.DtlCustomInventoryService.onInventoryClickEvent(DtlCustomInventoryService.java:67) ~[?:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor358.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:e20a51e]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:e20a51e]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:e20a51e]
at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2150) [pa.class:?]
at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) [lf.class:?]
at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) [lf.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_251]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_251]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:864) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:736) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

However it works perfect on spigot/paper of Minecraft 1.12.2.

Magma version 8d2a711

**Comment by kwright02** [comment]
Please edit your post and upload your log to https://mclo.gs This issue will be ignored until you do.

**Comment by kwright02** [comment]
Fixed in future release
