### ISSUE TITLE
[BUG] Performant and Phosphor incompatibility.

### ISSUE THREAD

**Issue by Zilacon** [magmafoundation/Magma#164]
Running server with phosphor only: OK
Running server with performant only: OK
Running server with both:
```
java.lang.ClassCastException: net.minecraft.world.WorldServer incompatible with me.jellysquid.mods.phosphor.api.ILightingEngineProvider
	at net.minecraft.world.chunk.Chunk.handler$zzg000$onConstructed(Chunk.java:1882)
	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:134)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:431)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:125)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:89)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:71)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:90)
	at net.minecraft.world.gen.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:128)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:100)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:147)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:486)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:456)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:316)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
	at java.lang.Thread.run(Thread.java:821)
```

Full crash report: https://mclo.gs/8t4YGWD

**Comment by kwright02** [comment]
@Zilacon please edit your post and upload your **FULL** log to https://mclo.gs

**Comment by Zilacon** [comment]
https://mclo.gs/8t4YGWD

**Comment by kwright02** [comment]
It's unkown at this time why this is the case, it seems that you have incompatible version working with eachother.
