### ISSUE TITLE
[BUG]Little Tiles Doors

### ISSUE THREAD

**Issue by WerelWolf** [magmafoundation/Magma#165]
**Describe the bug**
A clear and concise description of what the bug is:
There is a bug in the doors made with LittleTiles, when I create a door and interact with it, it bugs and gives an error
Logs: 
[22:36:07 INFO]: -------- World Settings For [Eberus] --------
[22:36:07 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[22:36:07 INFO]: Item Despawn Rate: 6000
[22:36:07 INFO]: Mob Spawn Range: 4
[22:36:07 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[22:36:07 INFO]: Nerfing mobs spawned from spawners: false
[22:36:07 INFO]: Item Merge Radius: 2.5
[22:36:07 INFO]: Experience Merge Radius: 3.0
[22:36:07 INFO]: View Distance: 10
[22:36:07 INFO]: Max TNT Explosions: 100
[22:36:07 INFO]: Random Lighting Updates: false
[22:36:07 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[22:36:07 INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[22:36:07 INFO]: Structure Info Saving: true
[22:36:07 INFO]: Cactus Growth Modifier: 100%
[22:36:07 INFO]: Cane Growth Modifier: 100%
[22:36:07 INFO]: Melon Growth Modifier: 100%
[22:36:07 INFO]: Mushroom Growth Modifier: 100%
[22:36:07 INFO]: Pumpkin Growth Modifier: 100%
[22:36:07 INFO]: Sapling Growth Modifier: 100%
[22:36:07 INFO]: Wheat Growth Modifier: 100%
[22:36:07 INFO]: NetherWart Growth Modifier: 100%
[22:36:07 INFO]: Vine Growth Modifier: 100%
[22:36:07 INFO]: Cocoa Growth Modifier: 100%
[22:36:07 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[22:36:07 INFO]: Arrow Despawn Rate: 1200
[22:36:07 INFO]: Zombie Aggressive Towards Villager: true
[22:36:07 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[22:36:07 ERROR]: Couldn't load chunk
 java.lang.ClassCastException: null
[22:36:07 INFO]: Negative index in crash report handler (0/20)
[22:36:07 FATAL]: Error executing task
 java.util.concurrent.ExecutionException: net.minecraft.util.ReportedException: Exception generating new chunk
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:864) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:736) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: net.minecraft.util.ReportedException: Exception generating new chunk
        at com.creativemd.creativecore.common.world.ChunkProviderFake.func_186025_d(ChunkProviderFake.java:139) ~[ChunkProviderFake.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:447) ~[amu.class:?]
        at net.minecraft.world.World.func_175726_f(World.java:442) ~[amu.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:2744) ~[amu.class:?]
        at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:61) ~[BlockSnapshot.class:d36c8c5]
        at com.creativemd.littletiles.common.util.place.Placement.place(Placement.java:128) ~[Placement.class:?]
        at com.creativemd.littletiles.common.util.place.Placement.tryPlace(Placement.java:145) ~[Placement.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.place(LittleDoorBase.java:216) ~[LittleDoorBase.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoorBase.openDoor(LittleDoorBase.java:294) ~[LittleDoorBase.class:?]
        at com.creativemd.littletiles.common.structure.type.door.LittleDoor.activate(LittleDoor.java:109) ~[LittleDoor.class:?]
        at com.creativemd.littletiles.common.packet.LittleActivateDoorPacket.executeServer(LittleActivateDoorPacket.java:123) ~[LittleActivateDoorPacket.class:?]
        at com.creativemd.creativecore.common.packet.PacketReciever$2.run(PacketReciever.java:115) ~[PacketReciever$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_251]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_251]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
Caused by: java.lang.ClassCastException
>

**Screenshots**
If applicable, add screenshots to help explain your problem:
![image](https://user-images.githubusercontent.com/67131150/85087272-721d3300-b1b3-11ea-814c-245d0a417462.png)
I created and interact, he bugs no longer goes back to where he was, and creates an invisible barrier not letting the player pass

![image](https://user-images.githubusercontent.com/67131150/85087287-7d705e80-b1b3-11ea-9cb3-179c6e4b8e9c.png)

Bug

**Info (please complete the following information):**
- Mod Name: LittleTiles
 - Mod Version: LittleTiles_v1.5.0-pre199_34_mc1.12.2.jar
 - Magma Version: vd36c8c5
 - OS:?

**Comment by kwright02** [comment]
@WerelWolf please edit your post with your log uploaded to https://mclo.gs

**Comment by WerelWolf** [comment]
https://mclo.gs/KT7LUvd

**Comment by kwright02** [comment]
@WerelWolf thanks for the link but please also edit your original post and remove the log you pasted in there and replace it with the URL for cleanliness.

**Comment by WerelWolf** [comment]
[latest.log](https://github.com/magmafoundation/Magma/files/4805293/latest.log)
I can't put on mclogs

**Comment by Adenser** [comment]
welp, I guess it's a little bit of a bump, but I can also report that magma is unable to handle littletilesmod correctly
 - Blocks crafted from recipe can bug/disappear but still exist on server/client-side, worldedit is required to remove them
- Animation on blocks is not working correctly, example door animation makes server think block still exist in the same place and user can't go through it where he should be able to

when changed back to the normal forge every works perfectly.

**Comment by LeviPawlak** [comment]
Hey @WerelWolf, I believe this was fixed. I can create doors without issues and by looking at the code it seemed someone fixed the line that was causing that error,
