### ISSUE TITLE
[BUG] TPS Command does not work on 1.12.2 Pack.

### ISSUE THREAD

**Issue by Zilacon** [magmafoundation/Magma#167]
I run 3 different modpacks, /tps works on RL Craft and Tekxit 3, but not 1.12.2 Pack.

From console:
```
[19:42:26 WARN]: Unexpected exception while parsing console command "tps"
 org.bukkit.command.CommandException: Unhandled exception executing 'tps' in org.magmafoundation.magma.commands.TPSCommand(tps)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[SimpleCommandMap.class:d36c8c5]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:d36c8c5]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:673) [CraftServer.class:d36c8c5]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:499) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:457) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:864) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:736) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at org.magmafoundation.magma.commands.TPSCommand.mean(TPSCommand.java:37) ~[TPSCommand.class:d36c8c5]
	at org.magmafoundation.magma.commands.TPSCommand.execute(TPSCommand.java:67) ~[TPSCommand.class:d36c8c5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[SimpleCommandMap.class:d36c8c5]
	... 7 more
```

From player:
```
[19:46:08 INFO]: Zilacon issued server command: /tps
[19:46:08 ERROR]: null
 org.bukkit.command.CommandException: Unhandled exception executing 'tps' in org.magmafoundation.magma.commands.TPSCommand(tps)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[SimpleCommandMap.class:d36c8c5]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:d36c8c5]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1615) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1450) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:864) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:736) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at org.magmafoundation.magma.commands.TPSCommand.mean(TPSCommand.java:37) ~[TPSCommand.class:d36c8c5]
	at org.magmafoundation.magma.commands.TPSCommand.execute(TPSCommand.java:67) ~[TPSCommand.class:d36c8c5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[SimpleCommandMap.class:d36c8c5]
	... 14 more
```

**Comment by wesleytech** [comment]
hi Zilacon,

in case you suspect your TPS is really low you could always use /forge tps or (if Cofh mods are installed) use /cofh tps

its not a fix, but a suggestion that could help in case its necessary

**Comment by kwright02** [comment]
Will be fixed in latest push.
