### ISSUE TITLE
[BUG] Issues with fake players and plugins.

### ISSUE THREAD

**Issue by Zilacon** [magmafoundation/Magma#188]
**Describe the bug**
**A clear and concise description of what the bug is:**
A "fake player" or TE using a "fake player" does anything on the server, it throws errors on Towny, GriefPrevention, Our custom econ plugin (We ended up patching our plugin to have fake player support), MCMMO, and AdvancedAchievements.

**To Reproduce**
**Steps to reproduce the behavior:**
Explained above.

**Expected behavior**
**A clear and concise description of what you expected to happen:**
Not to error.

**Info (please complete the following information):**
- Mod Name: Multiple Bukkit Plugins
 - Mod Version: 
 - Magma Version: 40c88e5
 - OS: Linux

**Additional context**
**Add any other context about the problem here:**
```
[00:59:19 ERROR]: Could not pass event PlayerChangePlotEvent to Towny v0.93.0.0
 org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:40c88e5]
	at org.bukkit.plugin.EventExecutor$$Lambda$2861/000000000BEEBF30.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:40c88e5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:40c88e5]
	at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMoveChunk(TownyPlayerListener.java:966) [Towny-1.12.2-PATCHED.jar:?]
	at com.palmergames.bukkit.towny.listeners.TownyPlayerListener.onPlayerMove(TownyPlayerListener.java:660) [Towny-1.12.2-PATCHED.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor355.execute(Unknown Source) [?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) [EventExecutor.class:40c88e5]
	at org.bukkit.plugin.EventExecutor$$Lambda$2861/000000000BEEBF30.execute(Unknown Source) [EventExecutor.class:40c88e5]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:40c88e5]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:40c88e5]
	at net.minecraft.network.NetHandlerPlayServer.processPlayer(NetHandlerPlayServer.java:837) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayer.processPacket(CPacketPlayer.java:33) [lk.class:?]
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.processPacket(CPacketPlayer.java:110) [lk$b.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:924) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:456) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:861) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at com.palmergames.bukkit.towny.TownySettings.getCapitalPrefix(TownySettings.java:983) ~[?:?]
	at com.palmergames.bukkit.towny.TownyFormatter.getFormattedTownName(TownyFormatter.java:634) ~[?:?]
	at com.palmergames.bukkit.towny.TownyFormatter.getFormattedName(TownyFormatter.java:613) ~[?:?]
	at com.palmergames.bukkit.towny.ChunkNotification.getAreaNotification(ChunkNotification.java:164) ~[?:?]
	at com.palmergames.bukkit.towny.ChunkNotification.getNotificationContent(ChunkNotification.java:123) ~[?:?]
	at com.palmergames.bukkit.towny.ChunkNotification.getNotificationString(ChunkNotification.java:112) ~[?:?]
	at com.palmergames.bukkit.towny.listeners.TownyCustomListener.onPlayerChangePlotEvent(TownyCustomListener.java:58) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor346.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:40c88e5]
	... 22 more
```
```
[01:04:17 ERROR]: Could not pass event BlockBreakEvent to mcMMO v1.6.4
 org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:f3a5280]
	at org.bukkit.plugin.EventExecutor$$Lambda$3820/00000000C394B4C0.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:f3a5280]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:507) [SimplePluginManager.class:f3a5280]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1234) [CraftEventFactory.class:f3a5280]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:131) [BlockEvent$BreakEvent.class:f3a5280]
	at com.buuz135.industrial.utils.BlockUtils.canBlockBeBroken(BlockUtils.java:98) [BlockUtils.class:?]
	at com.buuz135.industrial.tile.agriculture.CropRecolectorTile.work(CropRecolectorTile.java:109) [CropRecolectorTile.class:?]
	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:112) [WorkingAreaElectricMachine.class:?]
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280) [ElectricMachine.class:?]
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:120) [CustomElectricMachine.class:?]
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118) [ElectricTileEntity.class:?]
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.update(SidedTileEntity.kt:991) [SidedTileEntity.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2158) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:851) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:984) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:456) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:861) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
	at com.gmail.nossr50.util.StringUtils.getPrettyItemString(StringUtils.java:36) ~[?:?]
	at com.gmail.nossr50.util.StringUtils.getExplicitConfigMaterialDataString(StringUtils.java:338) ~[?:?]
	at com.gmail.nossr50.config.experience.ExperienceConfig.isSkillBlock(ExperienceConfig.java:213) ~[?:?]
	at com.gmail.nossr50.util.BlockUtils.affectedByGigaDrillBreaker(BlockUtils.java:165) ~[?:?]
	at com.gmail.nossr50.util.BlockUtils.shouldBeWatched(BlockUtils.java:26) ~[?:?]
	at com.gmail.nossr50.listeners.BlockListener.onBlockBreak(BlockListener.java:162) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:f3a5280]
	... 19 more
```

**Comment by kwright02** [comment]
We'll keep this one around in the archives, and I'll let everyone know when we've implemented support for this.
