### ISSUE TITLE
[BUG] PLZ Help. Decoder & Encoder Exceptions.

### ISSUE THREAD

**Issue by Zilacon** [magmafoundation/Magma#208]
Im running magma on bungeecord. Players are being kicked for encoder and decoder errors from the 1.12.2 servers only.
What causes these errors is unknown, it happens randomly to all players, and ultimately requires forcefully moving them when they login, or to delete their player data.

[18:01:16 INFO]: LocalAnesthesia lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)

Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[AbstractByteBuf.class:?]
    at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[AbstractByteBuf.class:?]
    at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:867) ~[gy.class:?]
    at net.minecraft.network.PacketBuffer.readVarInt(PacketBuffer.java:202) ~[gy.class:?]
    at net.minecraft.network.PacketBuffer.readEnumValue(PacketBuffer.java:187) ~[gy.class:?]
    at net.minecraft.network.play.client.CPacketEntityAction.readPacketData(SourceFile:30) ~[lq.class:?]
    at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40) ~[gz.class:?]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[ByteToMessageDecoder.class:?]

[14:47:48 INFO]: braddevans lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 3665718 into 3

These are all errors thrown from Magma itself, not bungee. Bungee does not show any errors on its console.
Any help solving this would be greatly appreciated.

EDIT: ☆꧁James꧂☆ on discord has the same issue, here is his error.
https://cdn.discordapp.com/attachments/679448221424156672/738976940006047834/unknown.png
His message: https://discordapp.com/channels/612695539729039411/679448221424156672/740279014299664405

**Comment by Amgelo563** [comment]
I believe Bungeecord is not compatible with Forge. You'd need forks like Hexacord or Waterfall.

**Comment by Zilacon** [comment]
We are using hexacord.

**Comment by Amgelo563** [comment]
Then I believe they'll need the Hexacord version as well so they can reproduce the problem.

**Comment by Zilacon** [comment]
@kwright02 Has direct access to our repository. We have a custom build which adds 1.5.2/1.6.4 support.

**Comment by TwilightGamerPro** [comment]
@Zilacon its with one of the libraries from one of the mods that is trying to access an event that either (A) doesn't exists or (B) exists but doesn't have the required coding for it to function which causes players not to connect, The same with the discord user James. I've already helped him figure out what library/api mod that was causing the issue for his since he is one of the head Plugin Dev's and Team manager. I have told him to list the mods that caused this that isn't supported by Magma to send off, i'd suggest disabling certain mods to see which one is actually causing this so that they can look into what that mod is trying to call into a bit more better so it can be resolved a bit more quickly. This has nothing to due with bungee-cord as bungee-cord does support forge connections if you setup the config correctly.  And there is a bungee plugin that can be developed to allow 1.5.2 to 1.10.2 clients to connect with certain packet events that i won't go into detail with. This is all that i can provide for now, sorry.

**Comment by kwright02** [comment]
Do you have any of the mod names that are incompatible?

**Comment by TwilightGamerPro** [comment]
> Do you have any of the mod names that are incompatible?

@kwright02 mine and slash and its lib dependency isn't compatible with it

**Comment by Zilacon** [comment]
I dont have that mod on any of my 3 servers, so it must be another.
I run RL Craft, Tekxit 3, and The 1.12.2 Pack

**Comment by TwilightGamerPro** [comment]
@Zilacon which modpack is it that's causing it, so i can try to get the same thing and i'll try to help if that's okay with the contributor's, to see which mod is causing it

**Comment by Zilacon** [comment]
Ive listed my 3 packs above, all 3 of them are getting this error.
RL Craft is a lot more rare then the other 2 though. Ive only had about 6 people from RL Craft get a decoder error. The other 2 are in the hundreds.

**Comment by TwilightGamerPro** [comment]
okay, i'll test all 3 of them and try to see which mod causes it for them to help you and to also help the contributors

**Comment by Zilacon** [comment]
Awesome man, ty!

**Comment by TwilightGamerPro** [comment]
@Zilacon can i ask is it the 2.8.2 beta of rlcraft?

**Comment by Zilacon** [comment]
Yes, i have the versions listed here: http://apocgaming.org/servers

**Comment by TwilightGamerPro** [comment]
Thanks, that helps a lot more, i'll start working on it rn since i have that version of rlcraft already installed and the other 2, it may take be awhile to respond back with what caused it

**Comment by Zilacon** [comment]
Alright.

**Comment by Zilacon** [comment]
Someone on RLC just got it when they first logged into the spawn:
```
[22:21:10 INFO]: jjawer logged in with entity id 72718 at ([Spawn]-3.627223271038726, 49.0, 6.794997680240049)
[22:21:43 ERROR]: NetworkDispatcher exception
 io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Thread.java:821) [?:1.8.0_252]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:867) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.func_150792_a(PacketBuffer.java:202) ~[gy.class:?]
	at net.minecraft.network.PacketBuffer.func_179257_a(PacketBuffer.java:187) ~[gy.class:?]
	at net.minecraft.network.play.client.CPacketEntityAction.func_148837_a(SourceFile:30) ~[lq.class:?]
	at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40) ~[gz.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[minecraft_server.1.12.2.jar:?]
	... 24 more
[22:21:43 INFO]: jjawer lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
```

**Comment by TwilightGamerPro** [comment]
yep its one of the mods api's/libs @Zilacon that's causing it

**Comment by TwilightGamerPro** [comment]
i am still going through to see which one it is, may i ask for rlcraft to disable on the server and client side any mods that add skills/abilities/magic and see if it continues but please do this on a test server so it doesn't ruin any world data

**Comment by Zilacon** [comment]
Theres no way for me to test this as it happens randomly, like i said. It cant just be reproduced.

**Comment by kwright02** [comment]
Based on everything I could bear to test, i've concluded this is specifically due to the use of hexacoord/bungeecord/proxy whatevers
