### ISSUE TITLE
Looking for libraries in the same folder as the .jar file

### ISSUE THREAD

**Issue by ZizzyZizzy** [magmafoundation/Magma#210]
Creating a new issue. #209 was dismissed and then closed without even an attempt to reproduce. I can't re-open that issue now.

**Describe the issue**
When the server starts, it looks for the libraries folder in the same location as the .jar file, despite the CWD path.

**To Reproduce**
jar file is /home/multicraft/jar/magma/Magma.jar
The rest of the files are in a private directory.

**Launch the jar, notice it downloads libraries, despite the libraries.version and libraries folder existing in the CWD; It's looking in the same folder as the jar file.**

```
$ pwd
/var/tmp/test
$ ls -al
total 29720
drwxr-xr-x  5 multicraft multicraft     4096 Aug  4 12:07 .
drwxrwxrwt  6 root       root         155648 Aug  4 11:53 ..
-rw-r--r--  1 multicraft multicraft     1050 Aug  4 09:15 bukkit.yml
-rw-r--r--  1 multicraft multicraft      593 Aug  4 09:11 commands.yml
drwxr-xr-x  2 multicraft multicraft     4096 Aug  4 09:14 config
-rw-r--r--  1 multicraft multicraft        9 Aug  4 09:11 eula.txt
-rw-r--r--  1 multicraft multicraft     2576 Aug  4 09:11 help.yml
drwxr-xr-x 11 multicraft multicraft     4096 Aug  4 09:10 libraries
-rw-r--r--  1 multicraft multicraft       10 Aug  4 09:10 libraries.version
-rw-r--r--  1 multicraft multicraft     1970 Aug  4 09:16 magma.yml
-rw-r--r--  1 multicraft multicraft 30222121 Aug  4 09:10 minecraft_server.1.12.2.jar
-rw-r--r--  1 multicraft multicraft        0 Aug  4 09:11 permissions.yml
drwxr-xr-x  3 multicraft multicraft     4096 Aug  4 09:11 plugins
-rw-r--r--  1 multicraft multicraft     3267 Aug  4 09:17 spigot.yml
-rw-r--r--  1 multicraft multicraft       74 Aug  4 09:12 .version
$  java -server -jar /home/multicraft/jar/magma/Magma.jar
Starting Magma
Downloading Server Libraries ...
Extracting Zip
/home/multicraft/jar/magma/
java.io.FileNotFoundException: /home/multicraft/jar/magma/libraries/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar (No such file or directory)
 at java.io.FileOutputStream.open0(Native Method)
 at java.io.FileOutputStream.open(FileOutputStream.java:270)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
 at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
 at org.magmafoundation.magma.downloads.DownloadServerFiles.unzip(DownloadServerFiles.java:117)
 at org.magmafoundation.magma.downloads.DownloadServerFiles.downloadServerLibraries(DownloadServerFiles.java:65)
 at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:56)
Checking for new version...
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
 at org.magmafoundation.magma.downloads.MagmaUpdater.<clinit>(MagmaUpdater.java:23)
 at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:61)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
 at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
 ... 2 more
```

**Expected behavior**
The server should look in the CWD, ignoring the absolute path of the server.jar file.

This is extremely important for shared hosting, since there is malware out there that will attempt to modify the server .jar file with more malware/DDOS utils. Moving the jar file out of the CWD and into a read-only location solves this problem.

**Additional context**
It should be noted that Craftbukkit, Spigot and PaperSpigot all honor the CWD when launching their jar file that has a completely different absolute path.

**Comment by kwright02** [comment]
You didn't need to open a separate ticket, we can reopen the other one.
