### ISSUE TITLE
Can I add gadgetsmenu support?[BUG]

### ISSUE THREAD

**Issue by qq591692157** [magmafoundation/Magma#219]
**Describe the bug**
A clear and concise description of what the bug is:
Could not load GadgetsMenu
**To Reproduce**
S22:23:57] [Server thread/ERROR] [Minecraft]: Error occurred while enabling GadgetsMenu v4.5.27 (Is it up to date?)
java.lang.NoSuchFieldError: field_191309_d
at com.yapzhenyie.GadgetsMenu.nms.v1_12_R1.pets.registry.NMSUtils.registerEntity(NMSUtils.java:209) ~[?:?]
at com.yapzhenyie.GadgetsMenu.nms.v1_12_R1.pets.registry.PetRegistry.registerPet(PetRegistry.java:113) ~[?:?]
at com.yapzhenyie.GadgetsMenu.nms.v1_12_R1.NMSManagerImpl.registerPets(NMSManagerImpl.java:88) ~[?:?]
at com.yapzhenyie.GadgetsMenu.GadgetsMenu.onEnable(GadgetsMenu.java:254) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Magma-dfb6bdf-server]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-Magma-dfb6bdf-server]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-Magma-dfb6bdf-server]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-Magma-dfb6bdf-server]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-Magma-dfb6bdf-server]
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name:
 - Mod Version: 
 - Magma Version: 
 - OS:

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
@qq591692157 please update the format of your post to correctly include everything as we've asked it to be.
