### ISSUE TITLE
[BUG] 100% one core load at idle

### ISSUE THREAD

**Issue by KweezyPlay** [magmafoundation/Magma#245]
**Describe the bug**
A clear and concise description of what the bug is:
after the update magma always uses one core at 100% load even at idle

**To Reproduce**
1. Run server with TerraFirmaCraft mod

**Expected behavior**
A clear and concise description of what you expected to happen:
~0% cpu load, as before magma update

**Screenshots**
If applicable, add screenshots to help explain your problem:
![Screenshot_20200909-000330](https://user-images.githubusercontent.com/36813920/92527594-ed7d0680-f22f-11ea-89b2-09f346e4164e.png)

**Info (please complete the following information):**
- Mod Name: TerraFirmaCraft
 - Mod Version: The latest from github
 - Magma Version: The latest from auto-updater
 - OS: Ubuntu 20.04.1 LTS (ARM64)

**Comment by 0H4rl3qu1n0** [comment]
Minecraft doesn't use more than one core. To make it use more than one please use jdk8 and 
https://gaming.stackexchange.com/questions/104527/how-can-i-run-a-minecraft-server-on-multiple-cpu-cores
Although that's just what i think your issue is.

**Comment by KweezyPlay** [comment]
no, you don't understand me, after the latest update it ALWAYS uses cpu, EVEN at idle. haven't had this before

**Comment by Amgelo563** [comment]
Can you try replicating the issue with a jar before the update, just by replacing the magma.jar with exact same setup?

**Comment by KweezyPlay** [comment]
ubuntu@ubuntu:~/magma$ java -jar Magma-76d7610-server.jar
Starting Magma
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/error/YAMLException
        at org.magmafoundation.magma.configuration.ConfigBase.<init>(ConfigBase.java:55)
        at org.magmafoundation.magma.configuration.MagmaConfig.<init>(MagmaConfig.java:83)
        at org.magmafoundation.magma.configuration.MagmaConfig.<clinit>(MagmaConfig.java:48)
        at org.magmafoundation.magma.downloads.DownloadServerFiles.getLibrariesVersion(DownloadServerFiles.java:100)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:55)
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.error.YAMLException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 5 more
ubuntu@ubuntu:~/magma$

older version says that

**Comment by Amgelo563** [comment]
Oh, disable autoupdate and try resetting the libraries as well.

**Comment by KweezyPlay** [comment]
![Screenshot_20200910-082732](https://user-images.githubusercontent.com/36813920/92685024-82baf080-f33f-11ea-9b4e-c51503af7588.png)
previous version, i don't have this problem

**Comment by KweezyPlay** [comment]
![Screenshot_20200910-083328](https://user-images.githubusercontent.com/36813920/92685409-518ef000-f340-11ea-9654-4ce211e09d46.png)
(same world, same mod)

**Comment by KweezyPlay** [comment]
do you need log?

**Comment by kwright02** [comment]
From the above screen shots it appears to have been fixed. If it's a bug with the latest version it will be removed in the next release
