### ISSUE TITLE
Harbor plugin spitting out error...

### ISSUE THREAD

**Issue by pixelblob** [magmafoundation/Magma#259]
|||||
[09:59:44] [Server thread/WARN] [xyz.nkomarn.Harbor.Harbor]: [Harbor] Task #24 for Harbor v1.6.1 generated an exception
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError:
        at xyz.nkomarn.Harbor.task.Checker.getSleeping(Checker.java:64) ~[?:?]
        at xyz.nkomarn.Harbor.task.Checker.checkWorld(Checker.java:31) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.DistinctOps$1$2.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_241]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_241]
        at xyz.nkomarn.Harbor.task.Checker.run(Checker.java:27) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[CraftTask.class:12a54a3]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:12a54a3]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:916) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:456) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:861) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError:
        ... 22 more
|||||

Plugins:
Autorestart-v4.jar
DiscordSRV-Build-1.19.1.jar
EssentialsX-2.18.1.0.jar
EssentialsXSpawn-2.18.1.0.jar
Harbor.jar
LagMonitor.jar
LuckPerms-Bukkit-5.1.107.jar
SimpleBackup-1.8.jar
SimpleRestart.jar
SkinsRestorer.jar
Vault.jar

Modlist and log linked below...
[latest.log](https://github.com/magmafoundation/Magma/files/5360750/latest.log)
[Modlist.txt](https://github.com/magmafoundation/Magma/files/5360751/Modlist.txt)
Magma Version: https://github.com/magmafoundation/Magma/releases/tag/v12a54a3

**Comment by kwright02** [comment]
I'm closing this issue because you didn't follow the format. Edit your ticket to follow the format and I will re-open it.
