### ISSUE TITLE
[BUG] Crash while checking libraries

### ISSUE THREAD

**Issue by bagomot** [magmafoundation/Magma#329]
**Describe the bug**
Crash while checking libraries. 

**Info (please complete the following information):**
 - Magma Version: 81f47df
 - OS: Windows 10 x64

**Crashlog**
```
Starting Magma
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/Lists
        at org.magmafoundation.magma.configuration.MagmaConfig.<init>(MagmaConfig.java:63)
        at org.magmafoundation.magma.configuration.MagmaConfig.<clinit>(MagmaConfig.java:48)
        at org.magmafoundation.magma.downloads.DownloadServerFiles.getLibrariesVersion(DownloadServerFiles.java:100)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:55)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
```

**Comment by bagomot** [comment]
This is due to the fact that the minecraft_server.1.12.2.jar file is not fully downloaded.

**Comment by kwright02** [comment]
delete everything and start a fresh installation
