### ISSUE TITLE
[Issue] Newest Build Compatibility Issue with EssentialX

### ISSUE THREAD

**Issue by NathanRodz92** [magmafoundation/Magma#341]
**Describe the issue**
A clear and concise description of what the bug is: Installed EssentialsX plugin and none of the commands work. /heal for example does not work. 

**To Reproduce**
1. Download 4a8d6af Magma Build, latest build
2. Install EssentialX plugin
Try "/heal"
See error: "An internal error occurred while attempting to perform this command"

**Expected behavior**
A clear and concise description of what you expected to happen:
[19:07:48] [Server thread/INFO] []: java.lang.NullPointerException
[19:07:48] [Server thread/ERROR] [net.minecraft.network.NetHandlerPlayServer]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'heal' in plugin Essentials v2.18.2.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[PluginCommand.class:4a8d6af]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:154) ~[SimpleCommandMap.class:4a8d6af]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:4a8d6af]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1615) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1450) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50) ~[la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11) ~[la.class:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_262]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_262]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:569) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:4a8d6af]
	... 15 more

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: N/A
 - Mod Version: N/A
 - Magma Version: This server is running Magma version 4a8d6af (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge Version 14.23.5.2855)
 - OS: 

**Additional context**
Add any other context about the problem here: It looks like the latest build conflicting with permissions within the server. I have also installed LuckPerms VER: 5.2.70. Any commands done within Essentials (v2.18.2.0) plugin does not work.

Logs: https://mclo.gs/kDjlGDm

**Comment by Hexeption** [comment]
Fixed
