### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by hoctz** [magmafoundation/Magma#345]
**Describe the issue**
A clear and concise description of what the bug is:

**To Reproduce**
1. Download bb50f45
2. Install ExecutableItems plugin Free/Premium Version, same result [https://www.spigotmc.org/resources/executableitems-1-12-1-16-custom-items-with-simple-gui.77578/]
3. Start the server
3. Use /ei-create <name/ID> [Create any item]
4. After create the item, try to open it again and save it [Save Button]
4. See error/issue

**Expected behavior**
A clear and concise description of what you expected to happen:
The plugin should save the item, but instead give the exact error

[Server thread/ERROR] [Minecraft]: Could not pass event InventoryClickEvent to ExecutableItems v2.6.5
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:bb50f45]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:bb50f45]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:bb50f45]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) ~[SimplePluginManager.class:bb50f45]
        at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2140) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
        at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:14) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:926) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NullPointerException
        at com.ssomar.executableitems.configs.ingame.items.ItemGUI.getHideAttributes(ItemGUI.java:486) ~[?:?]
        at com.ssomar.executableitems.configs.ingame.items.ItemGUIManager.saveItem(ItemGUIManager.java:682) ~[?:?]
        at com.ssomar.executableitems.configs.ingame.items.ItemGUIManager.clicked(ItemGUIManager.java:294) ~[?:?]
        at com.ssomar.executableitems.configs.ingame.InteractionGUI.onInvClick(InteractionGUI.java:61) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor114.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:bb50f45]
        ... 15 more

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Plugin Name: ExecutableItems
 - Mod Version:  2.6.5
 - Magma Version: bb50f45
 - OS: Linux

**Additional context**
Add any other context about the problem here:
The REQUIRE PREMIUM in logs it's just cause I'm sending a log from the free one, doesn't have that in the premium one, but still the same problem of the save stuff.

Latest log: https://mclo.gs/aUJfvNC

**Comment by kwright02** [comment]
Please edit the title of your ticket to include what the issue is. In this case it would be '[Bug] ExecutableItems InventoryClick Error'

**Comment by hoctz** [comment]
done ^^
