### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by rocogamer** [magmafoundation/Magma#351]
**Describe the issue**
Error in console

**To Reproduce**
1. Install StackMobs
4. See error/issue

**Screenshots**
```
[23:01:14] [Server thread/ERROR] [Minecraft]: Could not pass event EntityDeathEvent to StackMob v2.2.18
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:bb50f45]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:bb50f45]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:bb50f45]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) [SimplePluginManager.class:bb50f45]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:423) [CraftEventFactory.class:bb50f45]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:416) [CraftEventFactory.class:bb50f45]
        at net.minecraft.entity.EntityLivingBase.onDeath(EntityLivingBase.java:1342) [vp.class:?]
        at net.minecraft.entity.monster.EntityWitherSkeleton.onDeath(EntityWitherSkeleton.java:79) [ads.class:?]
        at net.minecraft.entity.EntityLivingBase.attackEntityFrom(EntityLivingBase.java:1152) [vp.class:?]
        at net.minecraft.entity.monster.EntityMob.attackEntityFrom(EntityMob.java:71) [ade.class:?]
        at WayofTime.bloodmagic.ritual.types.RitualWellOfSuffering.performRitual(RitualWellOfSuffering.java:91) [RitualWellOfSuffering.class:1.12.2-2.4.3-105]
        at WayofTime.bloodmagic.tile.TileMasterRitualStone.performRitual(TileMasterRitualStone.java:196) [TileMasterRitualStone.class:1.12.2-2.4.3-105]
        at WayofTime.bloodmagic.tile.TileMasterRitualStone.onUpdate(TileMasterRitualStone.java:69) [TileMasterRitualStone.class:1.12.2-2.4.3-105]
        at WayofTime.bloodmagic.tile.base.TileTicking.update(TileTicking.java:18) [TileTicking.class:1.12.2-2.4.3-105]
        at net.minecraft.world.World.redirect$zzj000$tileEntityUpdate(World.java:4527) [amu.class:?]
        at net.minecraft.world.World.updateEntities(World.java:2160) [amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:852) [oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:988) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NullPointerException
```

**Info (please complete the following information):**
- Plugin Name: StackMobs
 - Mod Version: Last
 - Magma Version: bb50f45
 - OS: Debian

**Comment by UeberallGebannt** [comment]
The latest version of StackMob only supports 1.15+
Are you sure that you are using the latest version?

**Comment by rocogamer** [comment]
That version I am using [https://www.spigotmc.org/resources/stackmob-legacy.61578/](https://www.spigotmc.org/resources/stackmob-legacy.61578/)

**Comment by LegitSoulja** [comment]
Also MobHunting and MobMoney

**Comment by joaoespanhol** [comment]
https://mclo.gs/EuYufeR

you need using last version magma.

no have this problem.

Log console:  no erro.

@Hexeption , your can't close ticket pleasse.
