### ISSUE TITLE
[BUG] SkinRestorer skin bug

### ISSUE THREAD

**Issue by SpeeeDCraft** [magmafoundation/Magma#384]
**Describe the bug**
A clear and concise description of what the bug is: When SkinRestorer is installed, I don't see my skin, but I see the skins of other people.

**To Reproduce**
1. Install a clean magma server
2. Install the SkinRestorer plugin
3. Install in the server.properties - online-mod=false. Log in to the world with a licensed account.
4. You will have the Alex skin.

**Info (please complete the following information):**
- Plugin Name: SkinRestorer 13.8.8
 - Magma Version: v045a413
 - OS: Windows 10

**Additional context**
Add any other context about the problem here:
logs:
[16:03:47] [Server thread/WARN] []: java.lang.NullPointerException
[16:03:47] [Server thread/WARN] []: 	at java.util.Objects.requireNonNull(Objects.java:203)
[16:03:47] [Server thread/WARN] []: 	at skinsrestorer.shared.utils.ReflectionUtil.invokeMethod(ReflectionUtil.java:163)
[16:03:47] [Server thread/WARN] []: 	at skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:205)
[16:03:47] [Server thread/WARN] []: 	at skinsrestorer.bukkit.skinfactory.OldSkinRefresher.accept(OldSkinRefresher.java:26)
[16:03:47] [Server thread/WARN] []: 	at skinsrestorer.bukkit.skinfactory.UniversalSkinFactory.lambda$updateSkin$1(UniversalSkinFactory.java:88)
[16:03:47] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65)
[16:03:47] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429)
[16:03:47] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:910)
[16:03:47] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[16:03:47] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:858)
[16:03:47] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:730)
[16:03:47] [Server thread/WARN] []: 	at java.lang.Thread.run(Thread.java:748)

**Comment by MakkuroJoKeRGod** [comment]
I have the same issue but with Biomes O' Plenty installed. After digging around, I found that there has been a similar issue in the past with SkinRestorer when installed with any biomes mod on magma. #108

**Comment by kwright02** [comment]
If offline mode is false skins won’t be loaded properly (I’m pretty sure)

**Comment by MakkuroJoKeRGod** [comment]
The entire point of SkinRestorer is to help load skins in offline mode.
