### ISSUE TITLE
[BUG] x not finite

### ISSUE THREAD

**Issue by bagomot** [magmafoundation/Magma#386]
**Describe the bug**
Random error with a random monster when attacking a player.

**To Reproduce**
Floating bug, I don't know how to repeat it with 100% probability. Happens when a monster attacks a player with a ranged attack.

**Info (please complete the following information):**
- Mod Name: any, vanilla 
 - Magma Version: 045a413
 - OS: any

**Additional context**
Error log:
```
[01:11:38] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exceptionjava.lang.IllegalArgumentException: x not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:115) ~[NumberConversions.class:a21e132]
        at org.bukkit.util.Vector.checkFinite(Vector.java:624) ~[Vector.class:a21e132]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.setVelocity(CraftEntity.java:381) ~[CraftEntity.class:a21e132]
        at net.minecraft.entity.EntityTrackerEntry.updatePlayerList(EntityTrackerEntry.java:348) ~[os.class:?]
        at net.minecraft.entity.EntityTracker.tick(EntityTracker.java:297) ~[ol.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1001) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:865) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: org.bukkit.util.NumberConversions = org.bukkit.util.NumberConversions = jar:file:/var/minecraft/server/server.jar!/org/bukkit/util/NumberConversions.class
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: org.bukkit.util.Vector = org.bukkit.util.Vector = jar:file:/var/minecraft/server/server.jar!/org/bukkit/util/Vector.class
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity = org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity = jar:file:/var/minecraft/server/server.jar!/org/bukkit/craftbukkit/v1_12_R1/entity/CraftEntity.class
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.entity.EntityTrackerEntry = os = jar:file:/var/minecraft/server/minecraft_server.1.12.2.jar!/os.class
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.entity.EntityTracker = ol = jar:file:/var/minecraft/server/minecraft_server.1.12.2.jar!/ol.class
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.server.MinecraftServer = net.minecraft.server.MinecraftServer = jar:file:/var/minecraft/server/minecraft_server.1.12.2.jar!/net/minecraft/server/MinecraftServer.class
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: net.minecraft.server.dedicated.DedicatedServer = nz = jar:file:/var/minecraft/server/minecraft_server.1.12.2.jar!/nz.class
[01:11:38] [Server thread/DEBUG] [org.dimdev.utils.ModIdentifier]: java.lang.Thread = java.lang.Thread = jar:file:/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/jre/lib/rt.jar!/java/lang/Thread.class
[01:11:38] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: /var/minecraft/server/./crash-reports/crash-2021-02-28_01.11.38-server.txt
[01:11:38] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
```
Crashlog file:
```
Description: Exception in server tick loop

java.lang.IllegalArgumentException: x not finite
    at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:115)
    at org.bukkit.util.Vector.checkFinite(Vector.java:624)
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.setVelocity(CraftEntity.java:381)
    at net.minecraft.entity.EntityTrackerEntry.updatePlayerList(EntityTrackerEntry.java:348)
    at net.minecraft.entity.EntityTracker.tick(EntityTracker.java:297)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1001)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:865)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
    at java.lang.Thread.run(Thread.java:748)
```
[crash-2021-02-28_01.11.38-server.txt](https://github.com/magmafoundation/Magma/files/6056378/crash-2021-02-28_01.11.38-server.txt)

**Comment by Doc94** [comment]
This is a Validation from Spigot, its not a bug.

**Comment by bagomot** [comment]
This crashes the server.
