### ISSUE TITLE
[BUG] startup - incompatible changes at opcode 731

### ISSUE THREAD

**Issue by FreekingDean** [magmafoundation/Magma#409]
**Describe the bug**
Startup failure I believe may have something to do with sponge?

**To Reproduce**
Launch utilizing the mc-eternal modpack.

**Expected behavior**
Server properly launches.

**Info (please complete the following information):**
- Mod Name: mc-eternal
 - Mod Version: 1.3.7.1
 - Magma Version: Magma Dev HEAD-1bc8635
 - OS: Windows10

**Additional context**
Relevant logs
```
[09:52:49] [main/ERROR] [mixin]: Critical injection failure: LVT in net/minecraft/world/World::func_72939_s()V has incompatible changes at opcode 731 in callback net/minecraft/world/World::beforeTick.
Expected: [Ljava/util/Iterator;, Lnet/minecraft/tileentity/TileEntity;, Lnet/minecraft/util/math/BlockPos;]
   Found: [I, Ljava/util/Iterator;, Lnet/minecraft/tileentity/TileEntity;]
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/world/World::func_72939_s()V has incompatible changes at opcode 731 in callback net/minecraft/world/World::beforeTick.
Expected: [Ljava/util/Iterator;, Lnet/minecraft/tileentity/TileEntity;, Lnet/minecraft/util/math/BlockPos;]
   Found: [I, Ljava/util/Iterator;, Lnet/minecraft/tileentity/TileEntity;]
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:487)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:437)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getMethod0(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getMethod(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:118)
[09:52:49] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:67)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:67]: java.lang.reflect.InvocationTargetException
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:67]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:67]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:67]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:67]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:118)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:67]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:67)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	at java.lang.Class.getMethod0(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	at java.lang.Class.getMethod(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:52:49] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:123]: 	... 6 more
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 15 more
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/world/World::func_72939_s()V has incompatible changes at opcode 731 in callback net/minecraft/world/World::beforeTick.
Expected: [Ljava/util/Iterator;, Lnet/minecraft/tileentity/TileEntity;, Lnet/minecraft/util/math/BlockPos;]
   Found: [I, Ljava/util/Iterator;, Lnet/minecraft/tileentity/TileEntity;]
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:487)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:437)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:377)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1273)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[09:52:49] [main/INFO] [STDERR]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 20 more

```

**Comment by kwright02** [comment]
We're going to need your full log because i'm unsure what mixin is causing this.
