### ISSUE TITLE
[BUG] NumberFormatException when starting magma

### ISSUE THREAD

**Issue by Almighty-Satan** [magmafoundation/Magma#410]
**Describe the bug**
Magma throws a NumberFormatException on startup

**To Reproduce**
Just start magma from the terminal

**Info (please complete the following information):**
 - No mods or plugins
 - Magma Version: 1bc8635
 - OS: Linux mint 20.1

**Additional context**
```
$ java -jar Magma-1bc8635-server.jar
Starting Magma
Checking for new version...
Failed to retrieve latest version.
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
	at jline.UnixTerminal.<init>(UnixTerminal.java:64)
	at jline.UnixTerminal.<init>(UnixTerminal.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:209)
	at jline.TerminalFactory.create(TerminalFactory.java:100)
	at jline.TerminalFactory.get(TerminalFactory.java:184)
	at jline.TerminalFactory.get(TerminalFactory.java:190)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:240)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:232)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:224)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:229)
	at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:83)
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1671)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:118)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:67)

[09:34:56] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[09:34:56] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[09:34:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[09:34:56] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
>[09:34:56] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_282, running on Linux:amd64:5.8.0-48-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[09:34:56] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[09:34:56] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[09:34:56] [main/WARN] [FML]: The coremod MagmaCorePlugin (org.magmafoundation.magma.MagmaCorePlugin) is not signed!
[09:34:56] [main/INFO] [FML]: 3 mod patches loaded!
[09:34:56] [main/INFO] [FML]: FirstAid loaded
[09:34:56] [main/INFO] [FML]: FTB-Quest loaded
[09:34:56] [main/INFO] [FML]: naturessompass loaded
[09:34:56] [main/INFO] [FML]: Searching /Magma/./mods for mods
[09:34:56] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:34:56] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:34:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:34:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:34:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:34:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:34:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:34:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:34:58] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:34:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:34:59] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[09:35:02] [main/INFO] [FML]: 3 patches loaded!
[09:35:02] [main/INFO] [FML]: Essentials [Fixes Commands in Essentials] loaded
[09:35:02] [main/INFO] [FML]: CoreProtect [Changes Material to Magma's getBlockMaterial that has modded block materials ] loaded
[09:35:02] [main/INFO] [FML]: dynmap [Remaps BukkitVersionHelperCB and BukkitVersionHelperGeneric to support Magma version] loaded
[09:35:02] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12.2
[09:35:02] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2855 Initialized
[09:35:02] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[09:35:02] [Server thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[09:35:03] [Server thread/INFO] [FML]: Replaced 1227 ore ingredients
[09:35:03] [Server thread/INFO] [FML]: Searching /Magma/./mods for mods
[09:35:03] [Server thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[09:35:03] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[09:35:03] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at CLIENT
[09:35:03] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge] at SERVER
[09:35:03] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[09:35:03] [Server thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[09:35:03] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[09:35:03] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[09:35:04] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[09:35:04] [Server thread/INFO] [FML]: Applying holder lookups
[09:35:04] [Server thread/INFO] [FML]: Holder lookups applied
[09:35:04] [Server thread/INFO] [FML]: Applying holder lookups
[09:35:04] [Server thread/INFO] [FML]: Holder lookups applied
[09:35:04] [Server thread/INFO] [FML]: Applying holder lookups
[09:35:04] [Server thread/INFO] [FML]: Holder lookups applied
[09:35:04] [Server thread/INFO] [FML]: Applying holder lookups
[09:35:04] [Server thread/INFO] [FML]: Holder lookups applied
[09:35:04] [Server thread/INFO] [FML]: Injecting itemstacks
[09:35:04] [Server thread/INFO] [FML]: Itemstack injection complete
[09:35:04] [Server thread/WARN] [FML]: Replacing net.minecraftforge.server.permission.DefaultPermissionHandler with org.magmafoundation.magma.commands.permission.BukkitPermissionsHandler
[09:35:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Loading properties
[09:35:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Default game type: SURVIVAL
[09:35:04] [Server thread/INFO] [Minecraft]: This server is running Magma version 1bc8635 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[09:35:04] [Server thread/INFO] [Minecraft]: Using 4 threads for Netty based IO
[09:35:04] [Server thread/INFO] [Spigot]: Server Ping Player Sample Count: 12
[09:35:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Generating keypair
[09:35:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting Minecraft server on 0.0.0.0:25565
[09:35:04] [Server thread/INFO] [net.minecraft.network.NetworkSystem]: Using epoll channel type
[09:35:04] [Server thread/INFO] [FML]: Applying holder lookups
[09:35:04] [Server thread/INFO] [FML]: Holder lookups applied
[09:35:04] [Server thread/INFO] [FML]: Injecting itemstacks
[09:35:04] [Server thread/INFO] [FML]: Itemstack injection complete
[09:35:04] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[09:35:04] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Preparing level "world"
[09:35:04] [Server thread/INFO] [FML.ModTracker]: This world was saved with mod forge version 14.23.5.2854 and it is now at version 14.23.5.2855, things may not work well
[09:35:04] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[09:35:04] [Server thread/INFO] [FML]: Applying holder lookups
[09:35:04] [Server thread/INFO] [FML]: Holder lookups applied
[09:35:05] [Server thread/INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[09:35:05] [Server thread/INFO] [Minecraft]: -------- World Settings For [world] --------
[09:35:05] [Server thread/INFO] [Minecraft]: Mob Spawn Range: 4
[09:35:05] [Server thread/INFO] [Minecraft]: Max TNT Explosions: 100
[09:35:05] [Server thread/INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[09:35:05] [Server thread/INFO] [Minecraft]: Cactus Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Cane Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Melon Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Sapling Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Wheat Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Vine Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[09:35:05] [Server thread/INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[09:35:05] [Server thread/INFO] [Minecraft]: Random Lighting Updates: false
[09:35:05] [Server thread/INFO] [Minecraft]: Structure Info Saving: true
[09:35:05] [Server thread/INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[09:35:05] [Server thread/INFO] [Minecraft]: Experience Merge Radius: 3.0
[09:35:05] [Server thread/INFO] [Minecraft]: Item Despawn Rate: 6000
[09:35:05] [Server thread/INFO] [Minecraft]: Item Merge Radius: 2.5
[09:35:05] [Server thread/INFO] [Minecraft]: Arrow Despawn Rate: 1200
[09:35:05] [Server thread/INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[09:35:05] [Server thread/INFO] [Minecraft]: View Distance: 10
[09:35:05] [Server thread/INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[09:35:05] [Server thread/INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[09:35:05] [Server thread/INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[09:35:05] [Server thread/INFO] [FML]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@16c0c1f4)
[09:35:05] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 488 advancements
[09:35:05] [Server thread/INFO] [Minecraft]: -------- World Settings For [DIM-1] --------
[09:35:05] [Server thread/INFO] [Minecraft]: Mob Spawn Range: 4
[09:35:05] [Server thread/INFO] [Minecraft]: Max TNT Explosions: 100
[09:35:05] [Server thread/INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[09:35:05] [Server thread/INFO] [Minecraft]: Cactus Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Cane Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Melon Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Sapling Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Wheat Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Vine Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[09:35:05] [Server thread/INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[09:35:05] [Server thread/INFO] [Minecraft]: Random Lighting Updates: false
[09:35:05] [Server thread/INFO] [Minecraft]: Structure Info Saving: true
[09:35:05] [Server thread/INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[09:35:05] [Server thread/INFO] [Minecraft]: Experience Merge Radius: 3.0
[09:35:05] [Server thread/INFO] [Minecraft]: Item Despawn Rate: 6000
[09:35:05] [Server thread/INFO] [Minecraft]: Item Merge Radius: 2.5
[09:35:05] [Server thread/INFO] [Minecraft]: Arrow Despawn Rate: 1200
[09:35:05] [Server thread/INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[09:35:05] [Server thread/INFO] [Minecraft]: View Distance: 10
[09:35:05] [Server thread/INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[09:35:05] [Server thread/INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[09:35:05] [Server thread/INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[09:35:05] [Server thread/INFO] [FML]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@16c0c1f4)
[09:35:05] [Server thread/INFO] [Minecraft]: -------- World Settings For [DIM1] --------
[09:35:05] [Server thread/INFO] [Minecraft]: Mob Spawn Range: 4
[09:35:05] [Server thread/INFO] [Minecraft]: Max TNT Explosions: 100
[09:35:05] [Server thread/INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[09:35:05] [Server thread/INFO] [Minecraft]: Cactus Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Cane Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Melon Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Sapling Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Wheat Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Vine Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[09:35:05] [Server thread/INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[09:35:05] [Server thread/INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[09:35:05] [Server thread/INFO] [Minecraft]: Random Lighting Updates: false
[09:35:05] [Server thread/INFO] [Minecraft]: Structure Info Saving: true
[09:35:05] [Server thread/INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[09:35:05] [Server thread/INFO] [Minecraft]: Experience Merge Radius: 3.0
[09:35:05] [Server thread/INFO] [Minecraft]: Item Despawn Rate: 6000
[09:35:05] [Server thread/INFO] [Minecraft]: Item Merge Radius: 2.5
[09:35:05] [Server thread/INFO] [Minecraft]: Arrow Despawn Rate: 1200
[09:35:05] [Server thread/INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[09:35:05] [Server thread/INFO] [Minecraft]: View Distance: 10
[09:35:05] [Server thread/INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[09:35:05] [Server thread/INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[09:35:05] [Server thread/INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[09:35:05] [Server thread/INFO] [FML]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@16c0c1f4)
[09:35:05] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for level 0 (Seed: -1209680676343411120)
[09:35:06] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 96%
[09:35:06] [Server thread/INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[09:35:06] [Server thread/INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[09:35:06] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (1.958s)! For help, type "help" or "?"
[09:35:06] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting Minecraft server on 0.0.0.0:25565
[09:35:06] [Server thread/INFO] [Minecraft]: Timings Reset
[09:35:06] [Server thread/INFO] [FML]: Unloading dimension -1
[09:35:06] [Server thread/INFO] [FML]: Unloading dimension 1
```

**Comment by Serega007RU** [comment]
The problem is still not solved, the error still exists on the Magma va549e0d-DEV version
