### ISSUE TITLE
[BUG] Staff facilities plugin

### ISSUE THREAD

**Issue by Mitsu13Ion** [magmafoundation/Magma#414]
**Describe the bug**
Staff facilities plugins don't work

**To Reproduce**
Install Stafffacilities
And Magma Dev HEAD-1bc8635

[13:29:57] [Server thread/ERROR] [Minecraft]: Could not pass event BlockBreakEvent to StaffFacilities v5.0.8
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68) ~[EventExecutor.class:48ec0a1]
	at org.bukkit.plugin.EventExecutor$$Lambda$3751/0x000000002fe1bb60.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:48ec0a1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:48ec0a1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:517) [SimplePluginManager.class:48ec0a1]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1234) [CraftEventFactory.class:48ec0a1]
	at net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent.<init>(BlockEvent.java:113) [BlockEvent$HarvestDropsEvent.class:48ec0a1]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:343) [ForgeEventFactory.class:48ec0a1]
	at vazkii.quark.tweaks.feature.RightClickHarvest.replant(RightClickHarvest.java:134) [RightClickHarvest.class:?]
	at vazkii.quark.tweaks.feature.RightClickHarvest.onCropClick(RightClickHarvest.java:184) [RightClickHarvest.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_715_RightClickHarvest_onCropClick_RightClickBlock.invoke(.dynamic) [?:48ec0a1]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:48ec0a1]
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) [LagGoggles-1.12.2-5.8-132.jar:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:48ec0a1]
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1138) [ForgeHooks.class:48ec0a1]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:542) [or.class:?]
	at thaumcraft.common.golems.GolemInteractionHelper.golemClick(GolemInteractionHelper.java:60) [GolemInteractionHelper.class:?]
	at thaumcraft.common.golems.seals.SealHarvest.onTaskCompletion(SealHarvest.java:139) [SealHarvest.class:?]
	at thaumcraft.common.golems.tasks.TaskHandler.completeTask(TaskHandler.java:114) [TaskHandler.class:?]
	at thaumcraft.common.golems.ai.AIGoto.updateTask(AIGoto.java:120) [AIGoto.class:?]
	at thaumcraft.common.golems.ai.AIGotoBlock.updateTask(AIGotoBlock.java:25) [AIGotoBlock.class:?]
	at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129) [xf.class:?]
	at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:807) [vq.class:?]
	at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2688) [vp.class:?]
	at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:609) [vq.class:?]
	at thaumcraft.common.golems.EntityThaumcraftGolem.onLivingUpdate(EntityThaumcraftGolem.java:277) [EntityThaumcraftGolem.class:?]
	at net.minecraft.entity.EntityLivingBase.TickCentral_TrueOnUpdateTick(EntityLivingBase.java:2509) [vp.class:?]
	at net.minecraft.entity.EntityLiving.TickCentral_TrueOnUpdateTick(EntityLiving.java:318) [vq.class:?]
	at thaumcraft.common.entities.construct.EntityOwnedConstruct.TickCentral_TrueOnUpdateTick(EntityOwnedConstruct.java:120) [EntityOwnedConstruct.class:?]
	at thaumcraft.common.golems.EntityThaumcraftGolem.TickCentral_TrueOnUpdateTick(EntityThaumcraftGolem.java:287) [EntityThaumcraftGolem.class:?]
	at com.github.terminatornl.tickcentral.api.TickHub.trueOnUpdate(TickHub.java:56) [TickHub.class:3.2]
	at com.github.terminatornl.laggoggles.Main.redirectOnUpdate(Main.java:102) [LagGoggles-1.12.2-5.8-132.jar:?]
	at thaumcraft.common.golems.EntityThaumcraftGolem.onUpdate(EntityThaumcraftGolem.java) [EntityThaumcraftGolem.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2340) [amu.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2294) [amu.class:?]
	at net.minecraft.world.World.redirect$updateEntity$zzn000(World.java:4513) [amu.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2076) [amu.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:852) [oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:988) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
Caused by: java.lang.NullPointerException
	at me.xtomyserrax.StaffFacilities.Listeners.FreezeListeners.onBreak(FreezeListeners.java:77) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor107.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:66) ~[EventExecutor.class:48ec0a1]
	... 42 more

**Comment by kwright02** [comment]
I'm closing this until you fix your post. Please never ever just paste the log contents in here. Link a Pastebin or something. Please.
