### ISSUE TITLE
[BUG] Update timeout causes crash

### ISSUE THREAD

**Issue by Kugge** [magmafoundation/Magma#415]
**Describe the bug**
Update timeout causes crash.

**To Reproduce**
1. Start
2. Go to console
It works sometimes.
The server internet speed is about 1GbpS

**Expected behavior**
A clear and concise description of what you expected to happen:
Server starting.

**Screenshots**
If applicable, add screenshots to help explain your problem:
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)
:/home/container$ java -Xms10240M -Xmx10240M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar
Starting Magma
Checking for new version...
java.net.ConnectException: Connection timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:284)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1068)
        at org.magmafoundation.magma.downloads.MagmaUpdater.versionChecker(MagmaUpdater.java:52)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:62)
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
```

**Info (please complete the following information):**
- Mod Name: None
 - Mod Version: None
 - Magma Version: Magma Dev HEAD-1bc8635
 - OS: Archlinux VPS

**Comment by Migmag789** [comment]
Hi ! I have got the same crash just now.

**Comment by UknownGino** [comment]
It seems to be an auto updater related crash. Try starting the server with the -dau flag

**Comment by Migmag789** [comment]
Thanks for the answer ! The problem is that I'm using a dedicated server and I can't add server parameters, what should I do ? (I tried disabling it in the config, and this did nothing).

**Comment by UknownGino** [comment]
> Thanks for the answer ! The problem is that I'm using a dedicated server and I can't add server parameters, what should I do ? (I tried disabling it in the config, and this did nothing).

How do you start your server? You use the command "java -jar Magma-xxxxxx.jar", right? If so, try to start it by writing this: "java -jar Magma-xxxxx.jar -dau"

**Comment by Migmag789** [comment]
Ok thank you ! The problem is that actually I start the server just by clicking a "start" button, but I sent the issue to the host service to help me. Thank you very much again :D

**Comment by Migmag789** [comment]
Hi, my host finally added the "-dau" flag as a server parameter, but it still don't work, with still the same problem...

**Comment by Migmag789** [comment]
Oh, this time, it doesn't even understand what the "-dau" flag is...
