### ISSUE TITLE
[BUG] Can't start my Serveur

### ISSUE THREAD

**Issue by MathisSkate** [magmafoundation/Magma#443]
**Describe the bug**
A clear and concise description of what the bug is:

I can't launch my serveur with PO3 Kappa since 3 days but I could before

**To Reproduce**
Take PO3 Kappa
Launch With Latest Magma Version

**Expected behavior**
A clear and concise description of what you expected to happen:
I wanna Launch my server

**Errors Logs**
Here is my error log

[20:37:49] [Timer-0/WARN] []: Exception in thread "Timer-0" 
[20:37:49] [Timer-0/WARN] []: java.lang.NullPointerException
[20:37:49] [Timer-0/WARN] []:   at org.bukkit.Bukkit.getOnlinePlayers(Bukkit.java:143)
[20:37:49] [Timer-0/WARN] []:   at org.magmafoundation.magma.Metrics.getServerData(Metrics.java:236)
[20:37:49] [Timer-0/WARN] []:   at org.magmafoundation.magma.Metrics.submitData(Metrics.java:268)
[20:37:49] [Timer-0/WARN] []:   at org.magmafoundation.magma.Metrics.access$000(Metrics.java:40)
[20:37:49] [Timer-0/WARN] []:   at org.magmafoundation.magma.Metrics$1.run(Metrics.java:197)
[20:37:49] [Timer-0/WARN] []:   at java.util.TimerThread.mainLoop(Timer.java:555)
[20:37:49] [Timer-0/WARN] []:   at java.util.TimerThread.run(Timer.java:505)

**Additional context**
Add any other context about the problem here:

**Comment by UeberallGebannt** [comment]
Please send your full log
