### ISSUE TITLE
[Bug]: Magma is missing the [org/slf4j/Logger] class.

### ISSUE THREAD

**Issue by ZakDank** [magmafoundation/Magma#481]
### What happened?

Magma does not seem to include the _org/slf4j/Logger_ class which prevents JDAlib from working with UltimateChat, rendering the discord relay useless. 

More info on the UltimateChat github:
https://github.com/FabioZumbi12/UltimateChat/issues/320#issuecomment-874431117

### Mods

JDALib / UltimateChat

### Mod Version

Any

### Magma Version

Magma-dce6a22-DEV

### OS

Linux

### Relevant log output

```shell
[UltimateChat]: Plugin UltimateChat v1.9.1 generated an exception while executing task 54
Console 14:23:48
java.lang.NoClassDefFoundError: org/slf4j/Logger
at jdalib.jda.internal.utils.IOUtil.(IOUtil.java:34) ~[?:?]
at jdalib.jda.api.JDABuilder.build(JDABuilder.java:1829) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.(UCDiscord.java:70) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.lambda$registerJDA$1(UChat.java:382) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[CraftTask.class:46f4149]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:46f4149]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [ServerSchedulerReportingWrapper.class:46f4149]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassNotFoundException: org.slf4j.Logger
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:46f4149]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:95) ~[PluginClassLoader.class:46f4149]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
```

**Comment by UeberallGebannt** [comment]
Late to the party, but I have a question:
This class isnt included in spigot either, if I'm correct.
Are you sure this isn't a class added by a library?
