### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by HiroWu1** [magmafoundation/Magma#484]
Im trying to make a minecraft server with magma but when creating it, it doesnt create any files like the eula.txt and gives me this error in the console
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x35a50a4c) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x35a50a4c
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

**Comment by LarcekGiglamesh** [comment]
make sure you follow the template when posting an issue report, using a proper title as well, otherwise it will be closed
