### ISSUE TITLE
Minecraft Server Error

### ISSUE THREAD

**Issue by GAMINGPUG2121** [magmafoundation/Magma#486]
Hello. When I start my server with your file I get the following error.

E:\MinecraftJE\Servers\Minecraft Magma Server>java -jar Magma-761933c-STABLE-server.jar nogui
Starting Magma
Checking for new version...
No update found, latest version: (dce6a22) current version: (dce6a22)
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:118)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:67)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

11:39:44.14 | E:\MinecraftJE\Servers\Minecraft Magma Server>pause
Press any key to continue . . .

Please tell me how to fix it if its possible. :)

**Comment by JustRed23** [comment]
It seems like you are using an outdated Java version. Please install a newer JDK version (I prefer JDK 11 since its Long Term Support rn) and try again.

**Comment by UeberallGebannt** [comment]
Magma 1.12.2 only supports Java 8.

**Comment by GAMINGPUG2121** [comment]
OK Ty for the help.
