### ISSUE TITLE
[Bug]: Magma server bug plugins 

### ISSUE THREAD

**Issue by OptimusZeGaming** [magmafoundation/Magma#505]
### What happened?

I have created a magma server 1.12.2 forge, with the following plugins EssentialsX 2.19.0, EssentialsProtect, EssentialsXSpawn, EssentialsXChat, FastAsyncWorldEdit, goBrush, GoPaint, Multiverse, VoxelSniper, WorldEdit. 

When I start the server, it produces no errors, but when I execute the /reload command it causes errors (see log below). With Essentials for example you can't even do a command without getting an error in the console. 

Can you help me?

### Mods

no mods intall

### Mod Version

no mods intall

### Magma Version

this is the latest version

### OS

Linux

### Relevant log output

```shell
[15:20:47] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/WorldEdit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/sk89q/worldedit/bukkit/WorldEditPlugin.createEditSession(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/EditSession; @28: invokevirtual
  Reason:
    Type 'com/sk89q/worldedit/bukkit/BukkitPlayer' (current frame, stack[1]) is not assignable to 'com/sk89q/worldedit/LocalPlayer'
  Current Frame:
    bci: @28
    flags: { }
    locals: { 'com/sk89q/worldedit/bukkit/WorldEditPlugin', 'org/bukkit/entity/Player', 'com/sk89q/worldedit/bukkit/BukkitPlayer', 'com/sk89q/worldedit/LocalSession', 'com/sk89q/worldedit/extent/inventory/BlockBag' }
    stack: { 'com/sk89q/worldedit/EditSessionFactory', 'com/sk89q/worldedit/bukkit/BukkitPlayer' }
  Bytecode:
    0x0000000: 2a2b b601 b84d b800 362c b601 bb4e 2d2c
    0x0000010: b601 c53a 04b8 0036 b601 c92c b601 cf2d
    0x0000020: b601 d319 042c b601 d93a 0519 05b6 01de
    0x0000030: 1905 b0                                

	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:788465c-DEV]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330) ~[SimplePluginManager.class:788465c-DEV]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [SimplePluginManager.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:322) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:808) [CraftServer.class:788465c-DEV]
	at org.bukkit.Bukkit.reload(Bukkit.java:542) [Bukkit.class:788465c-DEV]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:41) [ReloadCommand.class:788465c-DEV]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153) [SimpleCommandMap.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:674) [CraftServer.class:788465c-DEV]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/sk89q/worldedit/bukkit/WorldEditPlugin.createEditSession(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/EditSession; @28: invokevirtual
  Reason:
    Type 'com/sk89q/worldedit/bukkit/BukkitPlayer' (current frame, stack[1]) is not assignable to 'com/sk89q/worldedit/LocalPlayer'
  Current Frame:
    bci: @28
    flags: { }
    locals: { 'com/sk89q/worldedit/bukkit/WorldEditPlugin', 'org/bukkit/entity/Player', 'com/sk89q/worldedit/bukkit/BukkitPlayer', 'com/sk89q/worldedit/LocalSession', 'com/sk89q/worldedit/extent/inventory/BlockBag' }
    stack: { 'com/sk89q/worldedit/EditSessionFactory', 'com/sk89q/worldedit/bukkit/BukkitPlayer' }
  Bytecode:
    0x0000000: 2a2b b601 b84d b800 362c b601 bb4e 2d2c
    0x0000010: b601 c53a 04b8 0036 b601 c92c b601 cf2d
    0x0000020: b601 d319 042c b601 d93a 0519 05b6 01de
    0x0000030: 1905 b0                                

	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_292]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_292]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[PluginClassLoader.class:788465c-DEV]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[JavaPluginLoader.class:788465c-DEV]
	... 14 more
[15:20:47] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/goPaint.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldEdit
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [SimplePluginManager.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:322) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:808) [CraftServer.class:788465c-DEV]
	at org.bukkit.Bukkit.reload(Bukkit.java:542) [Bukkit.class:788465c-DEV]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:41) [ReloadCommand.class:788465c-DEV]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153) [SimpleCommandMap.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:674) [CraftServer.class:788465c-DEV]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[15:20:47] [Server thread/ERROR] [Minecraft]: Could not load 'plugins/goBrush 1.12.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldEdit
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [SimplePluginManager.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:322) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:808) [CraftServer.class:788465c-DEV]
	at org.bukkit.Bukkit.reload(Bukkit.java:542) [Bukkit.class:788465c-DEV]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:41) [ReloadCommand.class:788465c-DEV]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153) [SimpleCommandMap.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:674) [CraftServer.class:788465c-DEV]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[15:20:47] [Server thread/INFO] [com.boydti.fawe.bukkit.BukkitMain]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v21.03.26-b67f782-1287-22.3.10
[15:20:47] [Server thread/INFO] [com.earth2me.essentials.Essentials]: [Essentials] Loading Essentials v2.19.0
[15:20:47] [Server thread/INFO] [com.earth2me.essentials.protect.EssentialsProtect]: [EssentialsProtect] Loading EssentialsProtect v2.19.0
[15:20:47] [Server thread/INFO] [com.thevoxelbox.voxelsniper.VoxelSniper]: [VoxelSniper] Loading VoxelSniper v5.172.0-SNAPSHOT
[15:20:47] [Server thread/INFO] [com.earth2me.essentials.spawn.EssentialsSpawn]: [EssentialsSpawn] Loading EssentialsSpawn v2.19.0
[15:20:47] [Server thread/INFO] [com.earth2me.essentials.chat.EssentialsChat]: [EssentialsChat] Loading EssentialsChat v2.19.0
[15:20:47] [Server thread/INFO] [com.onarandombox.MultiverseCore.MultiverseCore]: [Multiverse-Core] Loading Multiverse-Core v2.5.0-b727
[15:20:47] [Server thread/ERROR] [org.bukkit.craftbukkit.v1_12_R1.CraftServer]: loader constraint violation: when resolving method "com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.<init>(Lcom/onarandombox/MultiverseCore/api/Core;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/onarandombox/MultiverseCore/MultiverseCore, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/onarandombox/MultiverseCore/utils/SimpleBlockSafety, have different Class objects for the type com/onarandombox/MultiverseCore/api/Core used in the signature initializing Multiverse-Core v2.5.0-b727 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method "com.onarandombox.MultiverseCore.utils.SimpleBlockSafety.<init>(Lcom/onarandombox/MultiverseCore/api/Core;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/onarandombox/MultiverseCore/MultiverseCore, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/onarandombox/MultiverseCore/utils/SimpleBlockSafety, have different Class objects for the type com/onarandombox/MultiverseCore/api/Core used in the signature
	at com.onarandombox.MultiverseCore.MultiverseCore.onLoad(MultiverseCore.java:255) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:327) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:808) [CraftServer.class:788465c-DEV]
	at org.bukkit.Bukkit.reload(Bukkit.java:542) [Bukkit.class:788465c-DEV]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:41) [ReloadCommand.class:788465c-DEV]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153) [SimpleCommandMap.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689) [CraftServer.class:788465c-DEV]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:674) [CraftServer.class:788465c-DEV]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[15:20:47] [Server thread/INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[15:20:47] [Server thread/INFO] [com.boydti.fawe.bukkit.BukkitMain]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v21.03.26-b67f782-1287-22.3.10
[15:20:48] [Server thread/INFO] []: (FAWE) ++++ HASH CHECK ++++
[15:20:48] [Server thread/INFO] []: (FAWE) https://addons.cursecdn.com/files/2431/372/worldedit-bukkit-6.1.7.2.jar
[15:20:48] [Server thread/INFO] []: (FAWE) CRVJCWGJJ6UK40CTGHXQVK2/3C9BBTOS25FWI0ZHD4S=
[15:20:48] [Server thread/WARN] []: org.bukkit.plugin.InvalidPluginException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/sk89q/worldedit/bukkit/WorldEditPlugin.createEditSession(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/EditSession; @28: invokevirtual
  Reason:
    Type 'com/sk89q/worldedit/bukkit/BukkitPlayer' (current frame, stack[1]) is not assignable to 'com/sk89q/worldedit/LocalPlayer'
  Current Frame:
    bci: @28
    flags: { }
    locals: { 'com/sk89q/worldedit/bukkit/WorldEditPlugin', 'org/bukkit/entity/Player', 'com/sk89q/worldedit/bukkit/BukkitPlayer', 'com/sk89q/worldedit/LocalSession', 'com/sk89q/worldedit/extent/inventory/BlockBag' }
    stack: { 'com/sk89q/worldedit/EditSessionFactory', 'com/sk89q/worldedit/bukkit/BukkitPlayer' }
  Bytecode:
    0x0000000: 2a2b b601 b84d b800 362c b601 bb4e 2d2c
    0x0000010: b601 c53a 04b8 0036 b601 c92c b601 cf2d
    0x0000020: b601 d319 042c b601 d93a 0519 05b6 01de
    0x0000030: 1905 b0                                

[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:330)
[15:20:48] [Server thread/WARN] []: 	at com.boydti.fawe.bukkit.BukkitMain.onEnable(BukkitMain.java:66)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:159)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:410)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:349)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:809)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.Bukkit.reload(Bukkit.java:542)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:41)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:674)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[15:20:48] [Server thread/WARN] []: 	at java.lang.Thread.run(Thread.java:748)
[15:20:48] [Server thread/WARN] []: Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/sk89q/worldedit/bukkit/WorldEditPlugin.createEditSession(Lorg/bukkit/entity/Player;)Lcom/sk89q/worldedit/EditSession; @28: invokevirtual
  Reason:
    Type 'com/sk89q/worldedit/bukkit/BukkitPlayer' (current frame, stack[1]) is not assignable to 'com/sk89q/worldedit/LocalPlayer'
  Current Frame:
    bci: @28
    flags: { }
    locals: { 'com/sk89q/worldedit/bukkit/WorldEditPlugin', 'org/bukkit/entity/Player', 'com/sk89q/worldedit/bukkit/BukkitPlayer', 'com/sk89q/worldedit/LocalSession', 'com/sk89q/worldedit/extent/inventory/BlockBag' }
    stack: { 'com/sk89q/worldedit/EditSessionFactory', 'com/sk89q/worldedit/bukkit/BukkitPlayer' }
  Bytecode:
    0x0000000: 2a2b b601 b84d b800 362c b601 bb4e 2d2c
    0x0000010: b601 c53a 04b8 0036 b601 c92c b601 cf2d
    0x0000020: b601 d319 042c b601 d93a 0519 05b6 01de
    0x0000030: 1905 b0                                

[15:20:48] [Server thread/WARN] []: 	at java.lang.Class.forName0(Native Method)
[15:20:48] [Server thread/WARN] []: 	at java.lang.Class.forName(Class.java:348)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
[15:20:48] [Server thread/WARN] []: 	... 18 more
[15:20:48] [Server thread/INFO] []: (FAWE) ====== INSTALL WORLDEDIT ======
[15:20:48] [Server thread/INFO] []: (FAWE) FAWE requires WorldEdit to function correctly
[15:20:48] [Server thread/INFO] []: (FAWE) Info: https://github.com/boy0001/FastAsyncWorldedit/releases/
[15:20:48] [Server thread/INFO] []: (FAWE) ===============================
[15:20:48] [Server thread/INFO] [com.earth2me.essentials.Essentials]: [Essentials] Enabling Essentials v2.19.0
[15:20:48] [Server thread/ERROR] [Essentials]: java.lang.LinkageError: loader constraint violation: when resolving method "com.earth2me.essentials.I18n.<init>(Lnet/ess3/api/IEssentials;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/earth2me/essentials/Essentials, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/earth2me/essentials/I18n, have different Class objects for the type net/ess3/api/IEssentials used in the signature
[15:20:48] [Server thread/WARN] []: java.lang.LinkageError: loader constraint violation: when resolving method "com.earth2me.essentials.I18n.<init>(Lnet/ess3/api/IEssentials;)V" the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) of the current class, com/earth2me/essentials/Essentials, and the class loader (instance of org/bukkit/plugin/java/PluginClassLoader) for the method's defining class, com/earth2me/essentials/I18n, have different Class objects for the type net/ess3/api/IEssentials used in the signature
[15:20:48] [Server thread/WARN] []: 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:241)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:159)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:408)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:410)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:349)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:810)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.Bukkit.reload(Bukkit.java:542)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:41)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:153)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:689)
[15:20:48] [Server thread/WARN] []: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:674)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
[15:20:48] [Server thread/WARN] []: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
[15:20:48] [Server thread/WARN] []: 	at java.lang.Thread.run(Thread.java:748)
[15:20:48] [Server thread/INFO] [com.earth2me.essentials.protect.EssentialsProtect]: [EssentialsProtect] Enabling EssentialsProtect v2.19.0
[15:20:48] [Server thread/ERROR] [com.earth2me.essentials.protect.EssentialsProtect]: [EssentialsProtect] Essentials not installed or failed to load. Essentials Protect is in emergency mode now.
```

**Comment by Xplodin** [comment]
dont /reload
it causes issues
