### ISSUE TITLE
[Bug]: Can't install galacticraft (wrongly duplicated mod detection)

### ISSUE THREAD

**Issue by SmokeURSS** [magmafoundation/Magma#516]
### What happened?

Trying to instal galacticraft in my magma server but its keeps crashing because it detects that GalacticraftCore and MicdoodleCore are the same mod.

### Mods

GalacticraftCore1.12.2-4.0.2.280
Micdoodlecore1.12.2-4.0.2.280

### Mod Version

1.12.2

### Magma Version

Latest stable release

### OS

Windows

### Relevant log output

```shell
Time: 24/01/22 01:54
Description: Exception in server tick loop

Duplicate Mods:
	galacticraftcore : C:\Users\franc\Downloads\Minecraft Mods server\.\mods\MicdoodleCore-1.12.2-4.0.2.280.jar
	galacticraftcore : C:\Users\franc\Downloads\Minecraft Mods server\.\mods\GalacticraftCore-1.12.2-4.0.2.280.jar

net.minecraftforge.fml.common.DuplicateModsFoundException
	at net.minecraftforge.fml.common.Loader.identifyDuplicates(Loader.java:437)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:399)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:539)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:102)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:169)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Rodrogamby** [comment]
I'm using Galacticraft on my server and this doesn't seem to be happening. Maybe your files are identical but with different names?
