### ISSUE TITLE
[BUG]Magma shutdown quickly

### ISSUE THREAD

**Issue by Brzjomo** [magmafoundation/Magma#77]
**Describe the bug**

**To Reproduce**
1. start server
2. See error

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Magma Version: 6604d7a
 - OS:win10

**Additional context**
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
at org.magmafoundation.magma.configuration.MagmaConfig.getString(MagmaConfig.java:134)
at org.magmafoundation.magma.downloads.DownloadServerFiles.getLibrariesVersion(DownloadServerFiles.java:88)
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:48)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 3 more

**Comment by kwright02** [comment]
Given that the latest is a dev build, try using one of the older builds. Your stability should be greatly improved.

**Comment by Brzjomo** [comment]
It turned out i forgot to put the 1.12.2 server.jar in the folder incase somebody wanna know.
