### ISSUE TITLE
[BUG] Agricraft Crash

### ISSUE THREAD

**Issue by NordicGamerFE** [magmafoundation/Magma#89]
**Describe the bug**

**To Reproduce**
added magma to a mc eternal server

**Expected behavior**
Exepcted it to work

**Screenshots**

**Info (please complete the following information):**
MC ETERNAL
 - newest of date of creation: 
 - LINUX VM:

**Additional context**
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AgriCraft (agricraft)
Caused by: java.lang.NoSuchMethodError: org.reflections.Reflections.getResources(Lcom/google/common/base/Predicate;)Ljava/util/Set;
    at com.agricraft.agricore.util.ResourceHelper.findResources(ResourceHelper.java:24)
    at com.infinityraider.agricraft.core.CoreHandler.preInit(CoreHandler.java:68)
    at com.infinityraider.agricraft.proxy.IProxy.preInitStart(IProxy.java:19)
    at com.infinityraider.infinitylib.InfinityMod.preInit(InfinityMod.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:599)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:103)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:169)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:668)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by johncsuti** [comment]
Try removing AgriCraft from you mod folder and trying again.

**Comment by lingfeishengtian** [comment]
The reason is because Agricraft uses Reflection 0.9.10 while Magma uses 0.9.12, you just have to change the dependency to 0.9.10 and all will be well, but Moving World has an error.
